import test from 'node:test';
import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';
import {readFileSync} from 'node:fs';
import {api} from '../worker/api.mjs';
function setup(){const sql=new DatabaseSync(':memory:');sql.exec('PRAGMA foreign_keys=ON');sql.exec(readFileSync(new URL('../drizzle/0000_outgoing_dorian_gray.sql',import.meta.url),'utf8'));
 const DB={prepare(query){let args=[];return {bind(...v){args=v;return this},async first(){return sql.prepare(query).get(...args)||null},async all(){return {results:sql.prepare(query).all(...args)}},async run(){return sql.prepare(query).run(...args)}}},async batch(items){sql.exec('BEGIN');try{const results=[];for(const q of items)results.push(await q.run());sql.exec('COMMIT');return results}catch(e){sql.exec('ROLLBACK');throw e}}};
 async function call(path,method='GET',body,user='owner',mail='owner@example.com',origin='https://entrega.test'){const h={'Content-Type':'application/json',origin};if(user){h['oai-authenticated-user-id']=user;h['oai-authenticated-user-email']=mail}const r=await api(new Request('https://entrega.test/api'+path,{method,headers:h,body:method==='GET'?undefined:JSON.stringify(body)}),{DB});return {status:r.status,data:await r.json()}}
 return {call,sql};}
test('project lifecycle persists tasks, delivery feedback and per-user isolation',async()=>{const {call,sql}=setup();
 const c=await call('/clients','POST',{name:'Client',email:'client@example.com'});assert.equal(c.status,201);
 const p=await call('/projects','POST',{title:'Film launch',client_id:c.data.id,due:'2026-10-10'});assert.equal(p.status,201);
 const pid=p.data.id;
 assert.equal((await call('/workspace','GET',null,'stranger')).data.projects.length,0);
 assert.equal((await call('/projects/'+pid,'GET',null,'stranger')).status,404);
 assert.equal((await call('/projects','POST',{title:'Stolen',client_id:c.data.id,due:'2026-10-10'},'stranger')).status,400);
 const task=await call('/projects/'+pid+'/tasks','POST',{title:'First cut'});assert.equal(task.status,201);
 assert.equal((await call('/tasks/'+task.data.id,'PATCH',{done:true},'stranger')).status,404);
 assert.equal((await call('/tasks/'+task.data.id,'PATCH',{done:true})).status,200);
 assert.equal((await call('/projects/'+pid)).data.tasks[0].done,1);
 assert.equal((await call('/projects/'+pid+'/deliveries','POST',{title:'V1',url:'javascript:alert(1)'})).status,400);
 const delivery=await call('/projects/'+pid+'/deliveries','POST',{title:'V1',url:'https://example.com/video',note:'First draft'});assert.equal(delivery.status,201);
 const details=(await call('/projects/'+pid)).data;assert.equal(details.project.status,'review');const token=details.deliveries[0].token;
 assert.equal((await call('/review/'+token,'GET',null,'stranger','stranger@example.com')).status,404);
 assert.equal((await call('/review/'+token,'POST',{decision:'approved'})).status,403);
 assert.equal((await call('/review/'+token,'GET',null,'client','client@example.com')).data.canReview,true);
 assert.equal((await call('/review/'+token,'POST',{decision:'changes',body:'Adjust the intro'},'client','client@example.com')).status,201);
 assert.equal((await call('/review/'+token,'POST',{decision:'approved'},'client','client@example.com')).status,201);
 const r=(await call('/review/'+token)).data;assert.equal(r.delivery.status,'approved');assert.equal(r.comments.length,2);
 assert.equal((await call('/projects/'+pid,'PATCH',{title:'Film launch',description:'Done',due:'2026-10-10',status:'archived'})).status,200);
 assert.equal((await call('/workspace')).data.projects[0].status,'archived');sql.close();
});
test('authentication, CSRF, validation, and payload limits reject unsafe writes',async()=>{const {call,sql}=setup();
 assert.equal((await call('/workspace','GET',null,null)).status,401);
 assert.equal((await call('/clients','POST',{name:'C',email:'client@example.com'},'owner','owner@example.com','https://evil.example')).status,403);
 assert.equal((await call('/clients','POST',{name:'C',email:'invalid'})).status,400);
 assert.equal((await call('/clients','POST',{name:'x'.repeat(18000),email:'client@example.com'})).status,413);
 const c=await call('/clients','POST',{name:"<script>alert('x')</script>",email:'client@example.com'});
 assert.equal(c.status,201);
 assert.equal((await call('/projects','POST',{title:'Bad date',client_id:c.data.id,due:'2026-02-30'})).status,400);
 assert.equal((await call('/workspace')).data.projects.length,0);sql.close();
});
